Packer hw6
Otus-DevOps-2023-05/mihasolod_infra pull request #6
Opened 2023-07-24 18:23 UTC by mihasolod

# Выполнено ДЗ №6

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Установлен Packer
 - В YC создан сервисный аккаунт
 - Сделан базовый шаблон packer
 - Сделан bake-образ
 - Выполнена параметризация
 - Сделан скрипт автоматического создания ВМ из образа

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2023-07-24 18:25 UTC, mihasolod commented
Приветствую!
Проверьте, пожалуйста.
:)

2023-07-26 16:18 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Нужно добавить фейковый ключик, так же сделать скрипты исполняемыми
ДЗ возвращаю на доработку

2023-07-26 16:48 UTC, mihasolod commented
Ключ добавил.
В методичке указано

Создайте IAM key и экспортируйте его в файл. Помните, что
файлы, содержащие секреты, необходимо хранить за пределами
вашего репозитория.

я и храню вне репозитария, в задании не нашел указаний указаний о добавлении фейкового ключа.

Скрипты уже имеют права на исполнение.

$ git ls-files --stage config-scripts/
100755 c3900135737f03c331d1cf2aa76f50d91301514d 0	config-scripts/create-reddit-vm.sh
100755 665d3e4e03f8ca521c973c88d2144fe58be22a2d 0	config-scripts/deploy.sh
100755 1c77acaf4924c42adc1dcc83585803e528ad5bd8 0	config-scripts/install_mongodb.sh
100755 d2113f284de7a6be7e1b82862a07e504027b13a5 0	config-scripts/install_ruby.sh

$ git ls-files --stage scripts/
100755 c7c6e3b76ff3e867211561b9ee1d72eeee5fdad7 0	scripts/deploy.sh
100755 e09d75fe48ec5274e7f4ea4ffc709a4cd53e7957 0	scripts/install_mongodb.sh
100755 fe7ab7e689043869a821d38f8e852875f60ab944 0	scripts/install_ruby.sh

2023-07-26 17:03 UTC, mihasolod commented
Поправил пути и расположение директорий.

2023-07-31 08:02 UTC, mrgreyves approved these changes
Здравствуйте!)
Теперь все хорошо =)
ДЗ принимаю ^_^

2023-07-31 12:01 UTC, merged